'use client';
import {useEffect,useRef,useState} from 'react';
import {db} from '@/lib/supabase';
export type SearchHit={source_type:'chapter'|'characters'|'story_bibles'|'notes'|'outline_items';source_id:string;title:string;excerpt:string};
const labels={chapter:'Bab',characters:'Karakter',story_bibles:'Story Bible',notes:'Catatan',outline_items:'Outline'};
export default function ProjectSearch({projectId,onOpen}:{projectId:string;onOpen:(hit:SearchHit)=>Promise<void>}){
 const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[hits,setHits]=useState<SearchHit[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[more,setMore]=useState(false),[searched,setSearched]=useState(false);
 const sequence=useRef(0);
 useEffect(()=>()=>{sequence.current++},[]);
 async function search(append=false){const q=append?submitted:query.trim();if(q.length<2||q.length>100)return;const request=++sequence.current;setBusy(true);setError('');const {data,error}=await db.rpc('search_project',{p_project_id:projectId,p_query:q,p_offset:append?hits.length:0});if(sequence.current!==request)return;setBusy(false);if(error){setError('Pencarian gagal. Coba lagi.');return}setSubmitted(q);setSearched(true);setHits(old=>append?[...old,...data.slice(0,20)]:data.slice(0,20));setMore(data.length>20)}
 async function open(hit:SearchHit){setBusy(true);setError('');try{await onOpen(hit)}catch{setError('Hasil tidak tersedia atau sudah diarsipkan. Cari ulang untuk memperbarui hasil.')}finally{setBusy(false)}}
 return <section className="planning project-search"><span className="eyebrow">PENCARIAN PROYEK</span><h1>Temukan detail ceritamu.</h1><p>Cari kata atau frasa pada data tersimpan. Pencarian ini tidak memakai AI dan tidak mengirim naskah ke model.</p><form className="row" onSubmit={e=>{e.preventDefault();void search()}}><input aria-label="Kata atau frasa pencarian" placeholder="Misalnya: surat di perpustakaan" required minLength={2} maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" disabled={busy}>Cari</button></form>{error&&<div className="notice" role="alert">{error}</div>}{busy&&<p role="status">Memuat…</p>}{searched&&<p role="status">{hits.length}{more?'+':''} hasil untuk “{submitted}”</p>}{searched&&!hits.length&&!busy&&<div className="notice">Tidak ada hasil. Coba kata yang lebih singkat atau periksa ejaan. Arsip dan versi lama tidak ikut dicari.</div>}<div className="search-results">{hits.map(hit=><button key={`${hit.source_type}-${hit.source_id}`} disabled={busy} onClick={()=>void open(hit)} className="search-result"><span className="eyebrow">{labels[hit.source_type]}</span><h2>{hit.title}</h2><p>{hit.excerpt}</p><span>Buka {labels[hit.source_type].toLowerCase()} →</span></button>)}</div>{more&&<button disabled={busy} className="secondary" onClick={()=>void search(true)}>Muat hasil berikutnya</button>}</section>
}
