'use client';
import {useEffect,useRef,useState} from 'react';
import {db} from '@/lib/supabase';
import type {Chapter} from './studio';
type Version={id:string;revision_number:number;title:string;created_at:string;plain_text?:string;content_json?:Record<string,unknown>};
export default function VersionHistory({chapter,onClose,onRestore}:{chapter:Chapter;onClose:()=>void;onRestore:(v:Version)=>Promise<boolean>}){
 const [versions,setVersions]=useState<Version[]>([]),[selected,setSelected]=useState<Version|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[more,setMore]=useState(false);
 const alive=useRef(true),request=useRef(0);
 useEffect(()=>{alive.current=true;void load(0);return()=>{alive.current=false;request.current++}},[chapter.id]);
 async function load(offset:number){setLoading(true);setError('');const {data,error}=await db.from('chapter_versions').select('id,revision_number,title,created_at').eq('chapter_id',chapter.id).eq('project_id',chapter.project_id).order('revision_number',{ascending:false}).range(offset,offset+24);if(!alive.current)return;setLoading(false);if(error){setError('Riwayat gagal dimuat. Coba lagi.');return}setVersions(old=>offset?[...old,...(data??[])]:data??[]);setMore(data?.length===25)}
 async function select(v:Version){const id=++request.current;setBusy(true);setError('');const {data,error}=await db.from('chapter_versions').select('*').eq('id',v.id).eq('chapter_id',chapter.id).eq('project_id',chapter.project_id).single();if(!alive.current||id!==request.current)return;setBusy(false);if(error){setError('Versi tidak dapat dibuka. Coba lagi.');return}setSelected(data)}
 async function restore(){if(!selected||busy)return;if(!confirm(`Pulihkan versi ${selected.revision_number}? Versi saat ini akan tetap disimpan dalam riwayat.`))return;setBusy(true);setError('');try{const ok=await onRestore(selected);if(!alive.current)return;if(ok)onClose();else setError('Pemulihan belum berhasil. Lihat pesan penyimpanan di bawah editor.')}catch{if(alive.current)setError('Koneksi terputus. Muat ulang bab untuk memeriksa hasil sebelum mencoba lagi.')}finally{if(alive.current)setBusy(false)}}
 function download(){if(!selected)return;const url=URL.createObjectURL(new Blob([selected.title+'\n\n'+selected.plain_text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`inkrya-versi-${selected.revision_number}.txt`;a.click();URL.revokeObjectURL(url)}
 return <section className="version-history" aria-label="Riwayat versi bab"><div className="row version-heading"><div><span className="eyebrow">RIWAYAT BAB</span><h2>Kembali ke versi sebelumnya.</h2></div><button className="secondary" disabled={busy} onClick={onClose}>Kembali menulis</button></div><p>Setiap penyimpanan menyimpan salinan versi sebelumnya. Memulihkan versi membuat revisi baru; riwayat tetap utuh.</p>{error&&<div className="notice" role="alert">{error}</div>}<div className="versions-layout"><aside>{versions.map(v=><button className={selected?.id===v.id?'nav active':'nav'} key={v.id} disabled={busy} onClick={()=>void select(v)}><span>Versi {v.revision_number}<small>{new Date(v.created_at).toLocaleString('id-ID')}</small></span></button>)}{loading&&<p role="status">Memuat riwayat…</p>}{!loading&&versions.length===0&&!error&&<p>Belum ada versi lama. Riwayat tersedia setelah bab disimpan.</p>}{!loading&&(more||error)&&<button className="secondary" disabled={busy} onClick={()=>void load(versions.length)}>{error?'Coba lagi':'Muat versi lebih lama'}</button>}</aside><div>{busy&&<p role="status">Memproses…</p>}{selected?<><div className="version-comparison"><article><h3>Versi {selected.revision_number}</h3><h4>{selected.title}</h4><div className="version-text">{selected.plain_text||'(Bab kosong)'}</div></article><article><h3>Saat ini · versi {chapter.revision_number}</h3><h4>{chapter.title}</h4><div className="version-text">{chapter.plain_text||'(Bab kosong)'}</div></article></div><div className="row"><button className="primary" disabled={busy} onClick={()=>void restore()}>Pulihkan versi {selected.revision_number}</button><button className="secondary" disabled={busy} onClick={download}>Unduh TXT</button></div></>:<p>Pilih versi untuk membandingkan teks dengan bab saat ini. Format asli tetap dipertahankan saat dipulihkan.</p>}</div></div></section>
}
